### PR TITLE
Upgrades jsdom to latest and a bunch of other dep upgrades

### PR DESCRIPTION
**Pull request by designfrontier**
This upgrades to jsdom@8.5.0 and corrects some descrepencies in
the tests that the upgrade introduced. It also upgrades other
dependencies to their latest.

Except for grunt... for now I am leaving that one alone.

Also upgrades the eslint file to the latest version and created a
.eslintignore file to remove the /tmp and /dist directories from
the eslint checks. eslint is much happier now.

Lastly swapped a switch statement for a simple ternary in t_call
because it reads a little easier.

### CODE REVIEW

**Comment by designfrontier** [comment]
Not sure exactly how you want to handle version for this. Probably a minor?

**Comment by designfrontier** [comment]
passes tests locally on node 4.4.3, 5.11.0, 6.0.0

**Comment by fivetanley** [comment]
Would you mind adding those node versions to the build matrix in the `.travis.yml` file so travis can test those for us in the future? https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against

**Comment by fivetanley** [comment]
Changes look good to me, but I don't really use this project anymore. I know it is heavily used at Instructure (I used to work there with @jenseng). I can add you as a collaborator to the repository if you'd like.

**Comment by designfrontier** [comment]
If you want to that's fine with me. I work at Instructure with @jenseng currently :-)

**Comment by fivetanley** [comment]
You should have commit access now. Happy hacking!! Let me know your npm email and I can add you there as well.

**Comment by designfrontier** [comment]
npm email: daniel@designfrontier.net

**Comment by fivetanley** [comment]
Ooops, I don't have publish. You'll have to access @jenseng. :P

**Comment by jenseng** [comment]
i wonder if it'd be worth bumping jsdom back to 3.x? otherwise you *have* to be on node 4 or later :shrug:

**Comment by jenseng** [comment]
i'll take a stab at it, it'd be nice to have a version of i18nliner-handlebars that can be used with either, so as to facilitate upgrading node

**Comment by jenseng** [comment]
no dice on old node :-/ ... #13 

went ahead and published 0.2.0 to npm

**Comment by designfrontier** [comment]
Fwiw node 4 will be the maintenance release in about 6 months and is
currently the LTS. So everyone should be moving to it if they aren't there
yet, and off of it in about 6 months. Theoretically.

**Pull request merged**
